Vagrant.configure("2") do |config|
  config.vm.define :ipa_client_manual do |ipa_client_manual|
    ipa_client_manual.vm.box = "fedora/31-cloud-base"
    ipa_client_manual.vm.network :private_network, :ip => "192.168.50.4", :libvirt__domain_name => "jesusmg.internal"

  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.qemu_use_session = false
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "main.yml"
  end
end