Vagrant.configure("2") do |config|
  config.vm.define :ipa_master do |ipa_master|
    ipa_master.vm.box = "fedora/31-cloud-base"
    ipa_master.vm.network :private_network, :ip => "192.168.50.2", :libvirt__domain_name => "jesusmg.internal"

  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 2048
    libvirt.qemu_use_session = false
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "main.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_command = "ansible-galaxy collection install -r %{role_file}"
  end
end