Vagrant.configure("2") do |config|
  config.vm.define :ipa_client_auto do |ipa_client_auto|
    ipa_client_auto.vm.box = "fedora/31-cloud-base"
    ipa_client_auto.vm.network :private_network, :ip => "192.168.50.3", :libvirt__domain_name => "jesusmg.internal"

  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.qemu_use_session = false
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "main.yml"
    ansible.inventory_path = "inventory.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_command = "ansible-galaxy collection install -r %{role_file}"
  end
end